services:
  frontend:
    build: ./plant-care-frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - plant-service
      - notification-service
    environment:
      - NEXT_PUBLIC_NOTIFICATION_SERVICE_URL=http://notification-service:4001
      - NEXT_PUBLIC_PLANT_SERVICE_URL=http://plant-service:4002
      - NEXT_PUBLIC_USER_SERVICE_URL=http://user-service:4003

  notification-service:
    build: ./microservices/notification-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001

  plant-service:
    build: ./microservices/plant-service
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - PORT=4002

  user-service:
    build: ./microservices/user-service
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=development
      - PORT=4003